To read:

* Introduction to Probability and Statistics: Principles and Applications for Engineering and the Computing Sciences
Milton, J. Susan; Arnold, Jesse
http://www.abebooks.com/9780072468366/Introduction-Probability-Statistics-Principles-Applications-007246836X/plp

This is the course book for the local CSE students in year 2, study
period 1 = the most recent maths course before the DSLsofMath
course. I want to read parts of it to get a feeling for what they have
been reading recently.

2016-10-22: up to page 98 (start of Chapter 4)
2016-10-20: up to page 74
2016-10-16: up to page 22.
2016-10-15: Started reading
* Real and Complex Analysis (Higher Mathematics Series) 3rd Edition
by Walter Rudin

2016-10-10: Up to page 17
2016-10-07: Read the first pages.

* A First Course in Chaotic Dynamical Systems
Theory and Experiment
Robert L. Devaney
https://westviewpress.com/books/a-first-course-in-chaotic-dynamical-systems/

** Ch. 1. A mathematical and Historical Tour
** Ch. 2. Examples of Dynamical Systems
** Ch. 3. Orbits
** Ch. 4. Graphical Analysis
** Ch. 5. Fixed and Periodic Points
** Ch. 6. Bifurcations
** Ch. 7. The Quadratic Family
** Ch. 8. Transition to Chaos
** Ch. 9. Symbolic Dynamics
** Ch. 10. Chaos
** Ch. 11. Sarkovskii's Theorem
** Ch. 12. The Role of the Critical Orbit
2016-10-16: Skimming.
** Ch. 13. Newton's Method
** Ch. 14. Fractals
** Ch. 15. Complex Functions
** Ch. 16. The Julia Set
** Ch. 17. The Mandelbrot Set
** Ch. 18. Further Projects and Experiments
** App. A. Mathematical Preliminaries
** App. B. Algorithms
** App. C. References
* “Keep definition, change category” — A practical approach to state-based system calculi
José Nuno Oliveiraa, Victor Cacciari Miraldob
http://www.sciencedirect.com/science/article/pii/S2352220815001443
file:/home/patrikj/Dropbox/To_read/Oliveira_KeepDef_ChangeCat_1-s2.0-S2352220815001443-main.pdf
* "Typing linear algebra: A biproduct-oriented approach"
Hugo Daniel Macedo (INRIA Paris-Rocquencourt), José N. Oliveira (HASLab)
http://arxiv.org/abs/1312.4818
file:/home/patrikj/Dropbox/To_read/Oliveira_TypingAlgebra_1-s2.0-S0167642312001402-main.pdf
* TFPIE 2014 by Scott N. Walck
https://wiki.science.ru.nl/tfpie/images/2/25/LearnPhysics.pdf
https://wiki.science.ru.nl/tfpie/images/4/4a/Tfpie2014_submission_6.pdf
* On Teaching How to Design Programs: Observations from a Newcomer, Norman Ramsey, ICFP 2014
  https://www.cs.tufts.edu/~nr/pubs/htdp-tablet.pdf
Started reading 2015-06-20.
Very well written and interesting.
* Painless Conjugate Gradient, J. R. Chewchuk
http://www.cs.cmu.edu/~quake-papers/painless-conjugate-gradient.pdf
A detailed explanation and illustration of the "Conjugate gradient" method for solving large sparse matrix equations.
* "Functional Differential Geometry", by Gerald Jay Sussman and Jack Wisdom
  https://mitpress.mit.edu/books/functional-differential-geometry
  https://groups.csail.mit.edu/mac/users/gjs/6946/calculus-indexed.pdf

Read:
* "How to Solve It", Polya
** 2015-11-19: Intro (1-30)
Polya's "How to Solve It"
+ 1. Understanding the problem (unknowns, data, conditions; *notation*)
+ 2. Devising a plan (seen it before? similar? split, reduce, generalise?)
+ 3. Carrying out the plan (and check each step)
+ 4. Looking back (examine the solution, check, reflect)
** 2015-11-20: Pages -80
** 2015-12-05: Pages -103
** 2015-12-12: Pages -123
** 2015-12-12: Pages -140
** 2015-12-13: Pages -160
** 2015-12-17: Pages -200
** 2015-12-20: Pages -220
** 2015-12-21: Pages -240
** 2015-12-23: Pages -260
