To read:
* “Keep definition, change category” — A practical approach to state-based system calculi
José Nuno Oliveiraa, Victor Cacciari Miraldob
http://www.sciencedirect.com/science/article/pii/S2352220815001443
file:/home/patrikj/Dropbox/To_read/Oliveira_KeepDef_ChangeCat_1-s2.0-S2352220815001443-main.pdf

* "Typing linear algebra: A biproduct-oriented approach"
Hugo Daniel Macedo (INRIA Paris-Rocquencourt), José N. Oliveira (HASLab)
http://arxiv.org/abs/1312.4818
file:/home/patrikj/Dropbox/To_read/Oliveira_TypingAlgebra_1-s2.0-S0167642312001402-main.pdf

* TFPIE 2014 by Scott N. Walck
https://wiki.science.ru.nl/tfpie/images/2/25/LearnPhysics.pdf
https://wiki.science.ru.nl/tfpie/images/4/4a/Tfpie2014_submission_6.pdf
* On Teaching How to Design Programs: Observations from a Newcomer, Norman Ramsey, ICFP 2014
  https://www.cs.tufts.edu/~nr/pubs/htdp-tablet.pdf

Started reading 2015-06-20.
Very well written and interesting.
* Painless Conjugate Gradient, J. R. Chewchuk
http://www.cs.cmu.edu/~quake-papers/painless-conjugate-gradient.pdf

A detailed explanation and illustration of the "Conjugate gradient" method for solving large sparse matrix equations.
* "How to Solve It", Polya
** 2015-11-19: Intro (1-30)
Polya's "How to Solve It"
+ 1. Understanding the problem (unknowns, data, conditions; *notation*)
+ 2. Devising a plan (seen it before? similar? split, reduce, generalise?)
+ 3. Carrying out the plan (and check each step)
+ 4. Looking back (examine the solution, check, reflect)
** 2015-11-20: Pages -80
** 2015-12-05: Pages -103
** 2015-12-12: Pages -123
** 2015-12-12: Pages -140
** 2015-12-13: Pages -160
** 2015-12-17: Pages -200
** 2015-12-20: Pages -220
** 2015-12-21: Pages -240
** 2015-12-23: Pages -260
* "Functional Differential Geometry", by Gerald Jay Sussman and Jack Wisdom
  https://mitpress.mit.edu/books/functional-differential-geometry
  https://groups.csail.mit.edu/mac/users/gjs/6946/calculus-indexed.pdf
