* Nya coaching för bättre resultat
John Whitmore
http://www.nok.se/Akademisk/Titlar/Ledarskap-organisation/Ledarskap-organisation/Nya-Coaching-for-battre-resultat/

Läsläxa i Chalmers ledarskapsprogram (nr 8, 2015-11-05 och framåt).
** Del 1: Principerna för coaching
*** 2015-11-13: Intro + kapitel 1: Vad är coaching?
*** 2015-11-15: Kapitel 2: Chefen som coach
*** 2015-11-17: Kapitel 3: Förändringens natur
*** 2015-11-18: Kapitel 4: Coachingens natur
*** 2015-11-18: Kapitel 5: Effektiva frågor
*** 2015-11-18: Kapitel 6: Frågesekvensen
*** 2015-11-22: Kapitel 7: Målformulering
*** 2015-11-22: Kapitel 8: Verkligheten - vad är det?
*** 2015-11-22: Kapitel 9: Vilka är alternativen?
*** 2015-11-23: Kapitel 10: Vad ska du göra?
** Del 2: Coachingens praktik
*** 2015-12-08: Kapitel 11: Vad menar vi med goda resultat?
*** 2015-12-10: Kapitel 12: Att lära sig och att ha roligt
*** 2015-12-12: Kapitel 13: Motivation och självtillit
*** 2015-12-12: Kapitel 14: Att coacha för mening och syfte
*** 2015-12-12: Kapitel 15: Feedback och utvärdering
*** 2015-12-12: Kapitel 16: Teamutveckling
*** 2015-12-12: Kapitel 17: Teamcoaching
*** Kapitel 18: Att övervinna hinder mot coaching
*** Kapitel 19: En mängd fördelar med coaching
** Del 3: Ledarskap för optimala resultat
*** Kapitel 20: Se, höra, växa
*** Kapitel 21: Grunden för ledarskap
*** Kapitel 22: Ledarskapets egenskaper
** Del 4: Omvandling genom transpersonell coaching
*** Kapitel 23: Emotionell intelligens
*** Kapitel 24: Verktyg inom trnaspersonell psykologi
*** Kapitel 25: Coaching för framtiden
** Appendix
* Kön, kropp, begär och teknik: Passion och instrumentalitet på två tekniska högskoleprogram
https://gupea.ub.gu.se/handle/2077/39621
Ottemo, Andreas

Citat sid. 99:
  "hur maskulinitet och teknik samproduceras inom högre teknisk utbildning"

Spännande och nyttig synvinkel: förutom tekniska kunskaper och
färdigheter får studenterna också med sig en bild av vad som är
maskulint och feminint (i relation till ingenjörsämnet).

Sid. 193: "kemiteknik som överraskning". Många studenter som lockas
till K av ett kemiintresse stöts bort av för mycket teknik.
* Akademins fyra rum - tankemodellen
(läst 2015-11-20)
Akademiska ledningsrum, Gunnar Jonnergård, Thomas Sewerin, Lisbeth Birgersson
http://document.chalmers.se/download?docid=00000000-0000-0000-0000-000046DEE943
http://www.chalmers.se/insidan/SV/arbetsredskap/chef/leda-medarbetare
** Linjen
** Nätverket
** Forskning
** Utbildning
* WASP application
Skummade igenom ansökan.
https://www.wallenberg.com/kaw/18-miljarder-kronor-till-forskning-om-autonoma-system-och-mjukvaruutveckling
https://www.wallenberg.com/kaw/en/sek-18-billion-research-autonomous-systems-and-software-development
