* Nya coaching för bättre resultat
John Whitmore
http://www.nok.se/Akademisk/Titlar/Ledarskap-organisation/Ledarskap-organisation/Nya-Coaching-for-battre-resultat/

Läsläxa i Chalmers ledarskapsprogram (nr 8, 2015-11-05 och framåt).
** 2015-11-13: Intro + kapitel 1: Vad är coaching?
** 2015-11-15: Kapitel 2: Chefen som coach
** 2015-11-17: Kapitel 3: Förändringens natur
** 2015-11-18: Kapitel 4: Coachingens natur
** Effektiva frågor
** Frågesekvensen
** Målformulering
** Verkligheten - vad är det?
** Vilka är alternativen?
** Vad ska du göra?
* Kön, kropp, begär och teknik: Passion och instrumentalitet på två tekniska högskoleprogram
https://gupea.ub.gu.se/handle/2077/39621
Ottemo, Andreas

Citat sid. 99:
  "hur maskulinitet och teknik samproduceras inom högre teknisk utbildning"

Spännande och nyttig synvinkel: förutom tekniska kunskaper och
färdigheter får studenterna också med sig en bild av vad som är
maskulint och feminint (i relation till ingenjörsämnet).

Sid. 193: "kemiteknik som överraskning". Många studenter som lockas
till K av ett kemiintresse stöts bort av för mycket teknik.
* Akademins fyra rum - tankemodellen
(läst 2015-11-20)
Akademiska ledningsrum, Gunnar Jonnergård, Thomas Sewerin, Lisbeth Birgersson
http://document.chalmers.se/download?docid=00000000-0000-0000-0000-000046DEE943
http://www.chalmers.se/insidan/SV/arbetsredskap/chef/leda-medarbetare
** Linjen
** Nätverket
** Forskning
** Utbildning
* WASP application
Skummade igenom ansökan.
https://www.wallenberg.com/kaw/18-miljarder-kronor-till-forskning-om-autonoma-system-och-mjukvaruutveckling
https://www.wallenberg.com/kaw/en/sek-18-billion-research-autonomous-systems-and-software-development
